import AutoTest , { BaseAutoTestKey , AutoTestErrorCode , AutoTestAttrCode } from "./autoTest/AutoTest";
import MController from "./common/MController";
import NodeUiConfig from "./common/NodeUiConfig";
import PageHideShow from "./common/PageHideShow";
import { StateMachine } from "./common/StateMachine";
import { TaskQueue , TaskManager } from "./common/TaskQueue";
import { Utils } from "./common/Utils";
import BaseLangConf , { LanguageType } from "./config/BaseLangConf";
import BaseUIConf , { BASEUIID } from "./config/BaseUIConf";
import { ConfigGroup } from "./config/ConfigGroup";
import Const from "./const/Const";
import Combox from "./customNode/Combox";
import ComboxItem from "./customNode/ComboxItem";
import ListView , { ListViewEvent } from "./customNode/ListView";
import ListViewItem from "./customNode/ListViewItem";
import { EventManager } from "./event/EventManager";
import Global from "./global/Global";
import DataCollectionMgr from "./httpreq/DataCollectionMgr";
import HttpRequest , { HttpType } from "./httpreq/HttpRequest";
import Keyboard from "./keyboard/Keyboard";
import LanguageComp , { IEnumLanyType , LanuguageItem } from "./language/LanguageComp";
import LanguageManager from "./language/LanguageManager";
import BehaviorRecord , { ReportType } from "./log/BehaviorRecord";
import { LogManager } from "./log/LogManager";
import { zLog } from "./log/zLog";
import Main from "./Main";
import NetDelay from "./netDelay/NetDelay";
import CommonProto from "./network/CommonProto";
import { DefStringProtocol } from "./network/NetInterface";
import { NetManager } from "./network/NetManager";
import { NetTipsType , NetNodeState , NetNode } from "./network/NetNode";
import { NetTips } from "./network/NetTip";
import { ProtocolHelper } from "./network/ProtocolHelper";
import { WebSock } from "./network/WebSock";
import NodePool from "./res/NodePool";
import ResKeeper from "./res/ResKeeper";
import { ResLeakChecker } from "./res/ResLeakChecker";
import { ResLoader } from "./res/ResLoader";
import { LoadResArgs , LoadRemoteArgs , LoadResMixArgs , ResUtils } from "./res/ResUtils";
import SoundManager , { ClipEnum , musicClip } from "./sound/SoundManager";
import TipsManager from "./ui/TipsManager";
import UIManager , { UIDefAni } from "./ui/UIManager";
import UIView , { UIShowTypes } from "./ui/UIView";
import UIDialog from "./ui/uiViews/UIDialog";
import View from "./ui/View";
import { PICQUALITY , ComUtils } from "./utils/ComUtils";
import { FsmUtil } from "./utils/FsmUtil";
import IntersectUtils from "./utils/IntersectUtils";
import { NodeUtils } from "./utils/NodeUtils";
import ObjectPool from "./utils/ObjectPool";
import SpineUtils from "./utils/SpineUtils";
import TimeUtil from "./utils/TimeUtil";

export class game {}

game['AutoTest'] = AutoTest;
game['BaseAutoTestKey'] = BaseAutoTestKey;
game['AutoTestErrorCode'] = AutoTestErrorCode;
game['AutoTestAttrCode'] = AutoTestAttrCode;
game['MController'] = MController;
game['NodeUiConfig'] = NodeUiConfig;
game['PageHideShow'] = PageHideShow;
game['StateMachine'] = StateMachine;
game['TaskQueue'] = TaskQueue;
game['TaskManager'] = TaskManager;
game['Utils'] = Utils;
game['BaseLangConf'] = BaseLangConf;
game['LanguageType'] = LanguageType;
game['BaseUIConf'] = BaseUIConf;
game['BASEUIID'] = BASEUIID;
game['ConfigGroup'] = ConfigGroup;
game['Const'] = Const;
game['Combox'] = Combox;
game['ComboxItem'] = ComboxItem;
game['ListView'] = ListView;
game['ListViewEvent'] = ListViewEvent;
game['ListViewItem'] = ListViewItem;
game['EventManager'] = EventManager;
game['Global'] = Global;
game['DataCollectionMgr'] = DataCollectionMgr;
game['HttpRequest'] = HttpRequest;
game['HttpType'] = HttpType;
game['Keyboard'] = Keyboard;
game['LanguageComp'] = LanguageComp;
game['IEnumLanyType'] = IEnumLanyType;
game['LanuguageItem'] = LanuguageItem;
game['LanguageManager'] = LanguageManager;
game['BehaviorRecord'] = BehaviorRecord;
game['ReportType'] = ReportType;
game['LogManager'] = LogManager;
game['zLog'] = zLog;
game['Main'] = Main;
game['NetDelay'] = NetDelay;
game['CommonProto'] = CommonProto;
game['DefStringProtocol'] = DefStringProtocol;
game['NetManager'] = NetManager;
game['NetTipsType'] = NetTipsType;
game['NetNodeState'] = NetNodeState;
game['NetNode'] = NetNode;
game['NetTips'] = NetTips;
game['ProtocolHelper'] = ProtocolHelper;
game['WebSock'] = WebSock;
game['NodePool'] = NodePool;
game['ResKeeper'] = ResKeeper;
game['ResLeakChecker'] = ResLeakChecker;
game['ResLoader'] = ResLoader;
game['LoadResArgs'] = LoadResArgs;
game['LoadRemoteArgs'] = LoadRemoteArgs;
game['LoadResMixArgs'] = LoadResMixArgs;
game['ResUtils'] = ResUtils;
game['SoundManager'] = SoundManager;
game['ClipEnum'] = ClipEnum;
game['musicClip'] = musicClip;
game['TipsManager'] = TipsManager;
game['UIManager'] = UIManager;
game['UIDefAni'] = UIDefAni;
game['UIView'] = UIView;
game['UIShowTypes'] = UIShowTypes;
game['UIDialog'] = UIDialog;
game['View'] = View;
game['PICQUALITY'] = PICQUALITY;
game['ComUtils'] = ComUtils;
game['FsmUtil'] = FsmUtil;
game['IntersectUtils'] = IntersectUtils;
game['NodeUtils'] = NodeUtils;
game['ObjectPool'] = ObjectPool;
game['SpineUtils'] = SpineUtils;
game['TimeUtil'] = TimeUtil;

window['game'] = game;